apiVersion: v1
kind: ServiceAccount
metadata:
  name: aca-sa
  namespace: aca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aca-role
  namespace: aca
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aca-rolebinding
  namespace: aca
subjects:
  - kind: ServiceAccount
    name: aca-sa
    namespace: aca
roleRef:
  kind: Role
  name: aca-role
  apiGroup: rbac.authorization.k8s.io
