import { AuditReport } from '../agents/audit.agent.js';

export interface ExportFormat {
  format: 'csv' | 'json' | 'markdown';
}

/**
 * Export audit report as CSV.
 */
export function exportToCSV(report: AuditReport): string {
  const headers = [
    'Control ID',
    'Status',
    'Findings',
    'Remediation Steps',
    'Evaluated At',
  ];

  const rows = report.results.map((r) => [
    r.controlId,
    r.status,
    (r.findings || []).join('; '),
    (r.remediationSteps || []).join('; '),
    r.evaluatedAt.toISOString(),
  ]);

  return [headers.join(','), ...rows.map((row) => row.map((cell) => `"${cell}"`).join(','))].join('\n');
}

/**
 * Export audit report as structured JSON.
 */
export function exportToJSON(report: AuditReport): string {
  return JSON.stringify(
    {
      timestamp: report.timestamp,
      summary: report.summary,
      results: report.results,
    },
    null,
    2
  );
}

/**
 * Export audit report as Markdown (auditor-friendly).
 */
export function exportToMarkdown(report: AuditReport): string {
  const passRate = Math.round((report.summary.compliantCount / report.summary.totalControls) * 100);

  let md = `# SOC 2 Compliance Audit Report\n\n`;
  md += `**Date:** ${report.timestamp.toISOString()}\n\n`;
  md += `## Summary\n\n`;
  md += `- **Total Controls:** ${report.summary.totalControls}\n`;
  md += `- **Compliant:** ${report.summary.compliantCount}\n`;
  md += `- **Non-Compliant:** ${report.summary.nonCompliantCount}\n`;
  md += `- **Not Evaluated:** ${report.summary.notEvaluatedCount}\n`;
  md += `- **Pass Rate:** ${passRate}%\n\n`;

  md += `## Detailed Results\n\n`;
  md += `| Control ID | Status | Findings | Remediation |\n`;
  md += `|------------|--------|----------|-------------|\n`;

  for (const result of report.results) {
    const findings = (result.findings || []).join('; ') || 'None';
    const remediation = (result.remediationSteps || []).join('; ') || 'None';
    md += `| ${result.controlId} | ${result.status} | ${findings} | ${remediation} |\n`;
  }

  if (report.remediations) {
    md += `\n## Remediation Activity\n\n`;
    for (const [controlId, outcome] of report.remediations) {
      md += `- **${controlId}**: ${outcome.success ? '✅' : '❌'} ${outcome.message}\n`;
      md += `  - Action: ${outcome.actionTaken}\n`;
    }
  }

  md += `\n---\n\n`;
  md += `*Generated by Autonomous Compliance Agent*\n`;

  return md;
}

/**
 * Generate an auditor-friendly HTML report.
 */
export function exportToAuditorHTML(report: AuditReport): string {
  const passRate = Math.round((report.summary.compliantCount / report.summary.totalControls) * 100);
  const statusColor = passRate === 100 ? '#22c55e' : passRate >= 70 ? '#f59e0b' : '#ef4444';

  const resultsRows = report.results.map((r) => {
    const statusClass = r.status === 'COMPLIANT' ? 'compliant' : r.status === 'NON_COMPLIANT' ? 'non-compliant' : 'not-evaluated';
    return `
      <tr class="${statusClass}">
        <td><strong>${r.controlId}</strong></td>
        <td><span class="status-badge ${statusClass}">${r.status}</span></td>
        <td>${(r.findings || []).join('<br>')}</td>
        <td>${(r.remediationSteps || []).join('<br>') || '—'}</td>
        <td>${new Date(r.evaluatedAt).toLocaleString()}</td>
      </tr>
    `;
  }).join('');

  const remediationSection = report.remediations
    ? `<div class="section">
        <h2>🛠️ Remediation Activity</h2>
        <div class="remediation-grid">
          ${Array.from(report.remediations.entries()).map(([controlId, outcome]) => `
            <div class="remediation-card ${outcome.success ? 'success' : 'failed'}">
              <div class="remediation-header">
                <span class="remediation-icon">${outcome.success ? '✅' : '❌'}</span>
                <strong>${controlId}</strong>
              </div>
              <p>${outcome.message}</p>
              <p class="remediation-action">${outcome.actionTaken}</p>
            </div>
          `).join('')}
        </div>
      </div>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>SOC 2 Audit Report — ${report.timestamp.toISOString().split('T')[0]}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', system-ui, sans-serif;
      background: #f8fafc;
      color: #1e293b;
      line-height: 1.6;
      padding: 40px;
    }
    .container { max-width: 1200px; margin: 0 auto; }
    .header {
      background: white;
      border-radius: 16px;
      padding: 32px;
      margin-bottom: 24px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .header h1 { font-size: 28px; margin-bottom: 8px; }
    .header-meta { color: #64748b; font-size: 14px; }
    .score-card {
      display: inline-flex;
      align-items: center;
      gap: 16px;
      margin-top: 16px;
      padding: 16px 24px;
      background: ${statusColor}15;
      border: 2px solid ${statusColor};
      border-radius: 12px;
    }
    .score-value { font-size: 36px; font-weight: 700; color: ${statusColor}; }
    .score-label { font-size: 14px; color: #64748b; }
    .stats-bar {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 16px;
      margin-bottom: 24px;
    }
    .stat-box {
      background: white;
      border-radius: 12px;
      padding: 20px;
      text-align: center;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .stat-box .number { font-size: 28px; font-weight: 700; }
    .stat-box .label { font-size: 12px; color: #64748b; text-transform: uppercase; }
    .section {
      background: white;
      border-radius: 16px;
      padding: 24px;
      margin-bottom: 24px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .section h2 { font-size: 18px; margin-bottom: 16px; }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 14px;
    }
    th {
      text-align: left;
      padding: 12px;
      font-size: 12px;
      text-transform: uppercase;
      color: #64748b;
      border-bottom: 2px solid #e2e8f0;
    }
    td {
      padding: 12px;
      border-bottom: 1px solid #e2e8f0;
      vertical-align: top;
    }
    tr:hover { background: #f8fafc; }
    .status-badge {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 20px;
      font-size: 12px;
      font-weight: 600;
      text-transform: uppercase;
    }
    .status-badge.compliant { background: #dcfce7; color: #166534; }
    .status-badge.non-compliant { background: #fee2e2; color: #991b1b; }
    .status-badge.not-evaluated { background: #fef3c7; color: #92400e; }
    .remediation-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
      gap: 16px;
    }
    .remediation-card {
      border: 1px solid #e2e8f0;
      border-radius: 12px;
      padding: 16px;
    }
    .remediation-card.success { border-left: 4px solid #22c55e; }
    .remediation-card.failed { border-left: 4px solid #ef4444; }
    .remediation-header { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }
    .remediation-action { font-size: 13px; color: #64748b; margin-top: 8px; }
    .footer {
      text-align: center;
      color: #94a3b8;
      font-size: 12px;
      padding: 24px;
    }
    @media print {
      body { background: white; padding: 20px; }
      .section { box-shadow: none; border: 1px solid #e2e8f0; }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🔒 SOC 2 Compliance Audit Report</h1>
      <div class="header-meta">Generated on ${report.timestamp.toLocaleString()} by Autonomous Compliance Agent</div>
      <div class="score-card">
        <div>
          <div class="score-value">${passRate}%</div>
          <div class="score-label">Pass Rate</div>
        </div>
      </div>
    </div>

    <div class="stats-bar">
      <div class="stat-box">
        <div class="number">${report.summary.totalControls}</div>
        <div class="label">Total Controls</div>
      </div>
      <div class="stat-box">
        <div class="number" style="color:#22c55e">${report.summary.compliantCount}</div>
        <div class="label">Compliant</div>
      </div>
      <div class="stat-box">
        <div class="number" style="color:#ef4444">${report.summary.nonCompliantCount}</div>
        <div class="label">Non-Compliant</div>
      </div>
      <div class="stat-box">
        <div class="number" style="color:#f59e0b">${report.summary.notEvaluatedCount}</div>
        <div class="label">Not Evaluated</div>
      </div>
    </div>

    <div class="section">
      <h2>📋 Detailed Results</h2>
      <table>
        <thead>
          <tr>
            <th>Control ID</th>
            <th>Status</th>
            <th>Findings</th>
            <th>Remediation</th>
            <th>Evaluated At</th>
          </tr>
        </thead>
        <tbody>${resultsRows}</tbody>
      </table>
    </div>

    ${remediationSection}

    <div class="footer">
      <p>Autonomous Compliance Agent v1.0.0 — Confidential Audit Report</p>
      <p>This report is intended for authorized auditors and compliance personnel only.</p>
    </div>
  </div>
</body>
</html>`;
}
